### ISSUE TITLE
connection read timeout will be ignored in AMQConnection

### ISSUE THREAD

**Issue by bohrqiu** [rabbitmq/rabbitmq-java-client#10]
hi,
there may be a bug in com.rabbitmq.client.impl.AMQConnection#start()。
in this method，after MainLoop start，default read timeout is 10s.
if there is  something wrong with the socket,_frameHandler.readFrame() while be null (line:515).then 
in handleSocketTimeout method, because of _heartbeat == 0, timeout excepiton will be ignored ,and this method
will retry and retry for ever.
please modify the default _heartbeat not quals to zero, thank you all.

**Comment by michaelklishin** [comment]
I don't think this is relevant in master. See `AMQConnection#setHeartbeat` and heartbeat value negotiation in `AMQConnection#start`. Unless you set both server and client heartbeat intervals to 0 (which means "no heartbeats"), the max value of the two will be used after connection tune, and once the handshake is completed, the negotiated value will be set by `AMQConnection#setHeartbeat`, including updating the frame handler.

Initial socket timeout is set to a (now configurable) handshake timeout.
