### ISSUE TITLE
String read as utf-8

### ISSUE THREAD

**Issue by ensirius** [rabbitmq/rabbitmq-java-client#102]
For some reason, i can't read string as utf-8. I tryed use ValueReader but problem happens in this class too.

```java
@Override
public void handleDelivery(String t, Envelope e, AMQP.BasicProperties p, byte[] b) throws IOException {
  try(DataInputStream in = new DataInputStream(new ByteArrayInputStream(b))) {
      System.out.println(in.readUTF());
  }
}
```

Works only if i read string like this:

```
System.out.println(in.readLine());
```

**Comment by ensirius** [comment]
Meh, and this solution read as 1 string

**Comment by michaelklishin** [comment]
@ensirius I fail to see how this is a client issue. Please use rabbitmq-users for open-ended discussions.

**Comment by ensirius** [comment]
becasue it's incorretcly read string that send via web service(or using any other client library)?

**Comment by michaelklishin** [comment]
@ensirius RabbitMQ and Java client operate with byte arrays. There is no RabbitMQ Java client code your snippet: you only use JDK classes.

**Comment by michaelklishin** [comment]
@ensirius I don't know what "web service" that is but RabbitMQ Java client uses byte arrays for bodies, as your code demonstrates. It does not assume any particular encoding. How you turn that into a string is up to you. Please check your facts and your own code.

`ValueReader` is meant to be used with attribute tables, not bodies. There is absolutely no functionality for turning message bodies into strings in the client: use JDK facilities for that.
