### ISSUE TITLE
Support for SRV records for service discovery

### ISSUE THREAD

**Issue by nnordrum** [rabbitmq/rabbitmq-java-client#104]
I don't know the internals well enough to really implement this "correctly", but I could see this being phased in in two parts:
1) resolution on startup--useful for CI testing where you're not going to have long-running processes that may  switch addresses/ports.
2) resolution with polling/etc. updates--not sure if the RecoveryAware would be the place?

I can separate into two issues if you want me to.

Thanks!

p.s. I can take a stab at 1 if you can suggest where "the best" place to implement it would be.

**Comment by michaelklishin** [comment]
Can we take a step back and clarify what this is for and whether it can actually be done without breaking the protocol?

**Comment by nnordrum** [comment]
Sure. I've got the following setup:
Consul for service registration/DNS
Docker Container running JBoss, registered at jboss.service.consul
Docker Container running RabbitMQ, registered at rabbitmq.service.consul

Instead of doing "docker run --link rabbitmq -p 8080 jboss" (abbreviated obviously), I would like to use the SRV record from Consul's DNS service to resolve the link.

querying rabbitmq.service.consul returns:
1 1 34567 host1234.node.dc1.consul.

so in this case, in JBoss, it would translate
`amqp://rabbitmq.service.consul/`
into
`amqp://host1234.node.dc1.consul.:34567/`
and then connect as usual.

that would be the scenario 1 as provided above and would be beneficial in CI. scenario 2 would likely be more complicated, but would likely provide little value for CI; its value would come from a production environment, but I'd be happy with just 1 and then rely on the current clustering for 2.

Technically, it "should" be more complicated while reading the SRV record(s), but given that its intended purpose would be automated testing, I would think just reading the first record would be sufficient.

**Comment by michaelklishin** [comment]
@nnordrum so your plan for the client is to make it perform DNS queries on start/connection initiation and periodically, is my understanding correct?

**Comment by nnordrum** [comment]
initially would be 1, periodically would be 2.

been digging into it and it looks like you'd do it in `com.rabbitmq.client.ConnectionFactory.setUri(URI uri)` for initially. my current attempt extends ConnectionFactory and overrides setUri (externalized because I want to continue running the stock client).

**Comment by michaelklishin** [comment]
@nnordrum OK, lets start with 1 and see how it goes. If we don't introduce a lot of complexity and any external dependencies, I'm all for improvements like this.

I suspect that for step 1 you'd want to look into `AMQConnection` and possibly `ConnectionFactory`. Possibly `SocketFrameHandler`, too.

**Comment by michaelklishin** [comment]
Also, we need to make sure that this is optional, e.g. if we fail to perform an SRV query, the client would continue as usual (by performing "regular" resolution queries, then trying to connect). In other words, that we don't break anything for existing projects.

**Comment by nnordrum** [comment]
yup. I'll get this working, and then fork the actual client, and then submit a PR.

What about adding into/extending Address? would that be a way to cover all of them? I could just change how getHost/getPort behave...

**Comment by michaelklishin** [comment]
No objections to extending `Address`.

**Comment by acogoluegnes** [comment]
@nnordrum with https://github.com/rabbitmq/rabbitmq-java-client/pull/169 you should only need to provide a custom implementation of `AddressResolver`. Would that work for you?

**Comment by acogoluegnes** [comment]
@nnordrum we implemented a AddressResolver based on a SRV query through https://github.com/rabbitmq/rabbitmq-java-client/pull/190. You can give it a shot before it's merged into stable and master.
