### ISSUE TITLE
Do not confirmSelect more than once per channel

### ISSUE THREAD

**Issue by sergio91pt** [rabbitmq/rabbitmq-java-client#1056]
### Is your feature request related to a problem? Please describe.

Reactor's RabbitMQ [`sendWithTypedPublishConfirms()`](https://github.com/reactor/reactor-rabbitmq/blob/5dde6ee8f51de48945ceddf5e533b6455503b45a/src/main/java/reactor/rabbitmq/Sender.java#L278-L290) always invokes the `confirmSelect()` method of the underlying channel which causes a blocking RPC call. 

This is especially detrimental to performance when sending a small amount of messages per Publisher/Flux, as the channel is put into confirm mode even if it already was (when using a channel pool).

Following [RabbitMQ's best practices](https://www.rabbitmq.com/tutorials/tutorial-seven-java.html#:~:text=Confirms%20should%20be%20enabled%20just%20once%2C%20not%20for%20every%20message%20published.), confirms should be enabled once per channel. In fact, there's no API to disable confirms once enabled on a channel.

### Describe the solution you'd like

`ChannelN` should keep track if `confirmSelect()` was successfully enabled, and if so, future invocations of this method return a `Confirm.SelectOk` without making a RPC call.

I can contribute a PR if there's interest in this solution 🙂

**Comment by acogoluegnes** [comment]
That's a fair improvement, feel free to submit a PR. Thanks!
