### ISSUE TITLE
Port relevant TestMain parts to JUnit

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-java-client#108]
`com.rabbitmq.examples.TestMain` is used as an integration test that doesn't use JUnit and tests things many of which are already covered by the rest of the suite. We need to move relevant bits to JUnit and remove the rest.

**Comment by michaelklishin** [comment]
I believe https://github.com/rabbitmq/rabbitmq-java-client/issues/174 should be fixed before this one.

**Comment by michaelklishin** [comment]
This still needs backporting => re-opening.

**Comment by acogoluegnes** [comment]
Backport to stable done.
