### ISSUE TITLE
Switch to NIO[2]

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-java-client#11]
Reported and discussed in some depth on [rabbitmq-discuss](http://rabbitmq.1065348.n5.nabble.com/Long-timeout-if-server-host-becomes-unreachable-td30275.html).

Internal bug tracker: `#23327`.

The only solution is switching to NIO. NIO would yield little improvement for the client the way it works today but worth moving to for this issue.

**Comment by arunvisw** [comment]
did we get this feature in?

**Comment by michaelklishin** [comment]
@arunvisw we close issues that are fixed or no longer relevant for other reasons. This one is not closed ;)

**Comment by arunvisw** [comment]
Would really appreciate if you can suggest some work arounds

**Comment by michaelklishin** [comment]
The [original thread](http://rabbitmq.1065348.n5.nabble.com/Long-timeout-if-server-host-becomes-unreachable-td30275.html) mentions a workaround.

**Comment by Hronom** [comment]
I were any progress on solving blocks by timeout?

**Comment by michaelklishin** [comment]
@Hronom I don't understand what "blocks by timeout" means but there is no way to avoid `Socket#write` blocking in some cases without a really ugly workaround provided in a thread linked above. The right thing to do is to switch to NIO and since this issue is open, that is not done.

**Comment by Hronom** [comment]
So switching to NIO helps to solve situation when `Channel#basicPublish` block thread where it called without any notification about that connection slowed down by flow state?

**Comment by michaelklishin** [comment]
@Hronom please get familiar with the original mailing list report. This has no relation to internal flow control (or generally speaking, flow control period). While flow control may make this more visible, it can be reproduced without flow control.

**Comment by michaelklishin** [comment]
We believe the original issue is addressed in https://github.com/rabbitmq/rabbitmq-java-client/pull/191 but we'll keep this issue open because switching to NIO is still something we are interested in.
