### ISSUE TITLE
Change System.err.println and exception.printStackTrace by Logging in ForgivingExceptionHandler.java

### ISSUE THREAD

**Issue by PatrickSauts** [rabbitmq/rabbitmq-java-client#113]
Message in the class ForgivingExceptionHandler.java like: 
System.err.println("Caught an exception during connection recovery!");
exception.printStackTrace(System.err);

should go throw the logger.
The user should be able to ignore those messages if he choose to using the logger configuration file.

**Comment by michaelklishin** [comment]
@PatrickSauts have you considered submitting a pull request?

**Comment by PatrickSauts** [comment]
I can do that yes. in a few hours.

**Comment by PatrickSauts** [comment]
I have a question though @michaelklishin.
No Logger is define in any part of the code but Tracer.java which actually does sysout.

Can I add a dependency on SLF4J ? Or do you have anything else in mind ?

**Comment by michaelklishin** [comment]
@PatrickSauts no, you can't. I've misread the title. We will file a separate issue about what should be used for logging, as we are very careful about introducing dependencies.

**Comment by vladhid** [comment]
Maybe you could at least add some method like

```java
void produceErrorMessage(String message, Throwable cause) {
    System.err.println(message);
    cause.printStackTrace();
}
```
 to `ForgivingExceptionHandler` so there would be one-point entry for choosing the way to write messages to logs?

**Comment by michaelklishin** [comment]
@vladhid see #114. We will add a logging library dependency.
