### ISSUE TITLE
Logging library integration

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-java-client#114]
Over the years the library has been 0-dependency but issues such as #113 and calls to introduce Metrics integration are pretty common now.

This issue is only about logging. Should we use SLF4J? Or some kind of handlers for apps to hook into (was discussed for .NET client, for example). It remains to be discussed and decided.

**Comment by michaelklishin** [comment]
I think we should address this after #37, because managing dependencies with Ant is nowhere near as straightforward as with Gradle.

**Comment by xuwei-k** [comment]
+1 use slf4j

**Comment by michaelklishin** [comment]
OK, SLF4J it is then. We are convinced it's a much better idea to have logging compared to having 0 dependencies (the same goes for metrics).
