### ISSUE TITLE
RabbitMQ-client pro-guard configuration

### ISSUE THREAD

**Issue by zivalifestyle** [rabbitmq/rabbitmq-java-client#115]
I am using RabbitMQ-client for my Android app. Everything is working fine. But now I am facing issue while integrating Pro-guard to my application, kindly share the Pro-guard configuration for RabbitMQ-client.

Thanks in Advance!

**Comment by michaelklishin** [comment]
I don't think we have a Pro guard configuration for our client, or even know what it is.

Please ask questions on rabbitmq-users.
