### ISSUE TITLE
Support dynamic versioning

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/rabbitmq-java-client#123]
With the move to Maven (#37), the client version number is now hard-coded in `pom.xml`. We need a way to make this number dynamic so we can supply it from the environment or on the command line.

**Comment by dumbbell** [comment]
Here is an article (and three articles linked inside), pointed out by @michaelklishin, which could help:
https://axelfontaine.com/blog/final-nail.html

**Comment by michaelklishin** [comment]
I believe this can be closed in favour of managing the version with Maven. Now that the master of this client is no longer tied to RabbitMQ server releases, we can rely on that. @dumbbell @acogoluegnes WDYT?

**Comment by acogoluegnes** [comment]
@dumbbell @michaelklishin LGTM
