### ISSUE TITLE
Implement Closable interface

### ISSUE THREAD

**Issue by Khazrak** [rabbitmq/rabbitmq-java-client#131]
Channel and Connection can implement the Closable interface, the close()-method is already implemented. This will open up the possibility to compile with Java 7 and use the try-with-resource function to avoid try-catch in finally-block of close

**Comment by michaelklishin** [comment]
I think you are confusing `Closable` with `AutoCloseable`, which is used by try-with-resource. In any case, we cannot require JDK 7 yet. We will be able to once Spring drops JDK 6 compatibility.

**Comment by michaelklishin** [comment]
We don't have a tag for `will be fixed eventually but the time hasn't come yet` and we try to keep issues only to things that are actionable in the next release or two. Here we can't really know when we'd be able to do this => closing.

**Comment by Khazrak** [comment]
Closable is JDK 6 and in JDK 7 Closeable extends AutoCloseable, so it would come automatically with the switch. This would also mean that one could download the source and just compile it with JDK 7 and get AutoCloseable

**Comment by michaelklishin** [comment]
Fair enough. @Khazrak feel free to submit a PR against master.

**Comment by michaelklishin** [comment]
Fixed in #133 and will be out with `3.7.0`, thank you, @Khazrak!
