### ISSUE TITLE
Make socket connection to try all DNS record IPs

### ISSUE THREAD

**Issue by ebuildy** [rabbitmq/rabbitmq-java-client#138]
In a HA RabbitMQ cluster, I use DNS round robin technic to load balance the load between nodes and replace HAProxy, for instance:

rabbitmq => 10.0.0.1 10.0.0.2 10.0.0.3

It works like a charm with the Php extension, because here:

https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_socket.c#L449

We can see that all IP adresses from DNS record are "tested", so if a node goes down, no problemo, no error on Php side when connecting. 

But, I also use logstash to consume RabbitMQ messages, which uses this library, and apparently, this little trick is not working as I can see on:

https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/impl/FrameHandlerFactory.java#L28

Do you think this could be a feature here (or I may miss a Java trick here) ?

Thanks you,

**Comment by michaelklishin** [comment]
It's worth investigating if this client could do a similar thing.

**Comment by acogoluegnes** [comment]
@ebuildy Maybe this can be achieved with a custom implementation of the interface introduced in https://github.com/rabbitmq/rabbitmq-java-client/pull/169

**Comment by ebuildy** [comment]
Yeah ! Looks pretty good, thanks, i will work on the logstash plugin to
implement this .

Le 22 août 2016 4:56 PM, "Arnaud Cogoluègnes" <notifications@github.com> a
écrit :

**Comment by michaelklishin** [comment]
@ebuildy to make it clear that we would be interested in making this a core feature but would like to understand how exact you would like it to work. Given that this is an interface that can have multiple implementations, the risk for us in including something in the core is quite low.

**Comment by acogoluegnes** [comment]
@ebuildy [your changes](https://github.com/ebuildy/rabbitmq-java-client/commit/b59ce5681257808eda1dfde2ac9da6b729e3fc5d) could actually be in a custom implementation of `AddressResolver`. That would leave the `FrameHandlerFactory` unchanged.

**Comment by michaelklishin** [comment]
This feature has an unfortunate side-effect: it makes peer verification (as in TLS) based on hostname comparison next to impossible to do in many environments.

We will disable this resolver by default in a future 4.x and 5.x minor releases and not use it by default as of 6.0. It's a nice feature but TLS peer verification is a lot more popular and arguably important.
