### ISSUE TITLE
Makefile uses archived rabbitmq-codegen repository

### ISSUE THREAD

**Issue by tomodachi94** [rabbitmq/rabbitmq-java-client#1486]
### Describe the bug

`Makefile` uses the archived repository (https://github.com/rabbitmq/rabbitmq-codegen):
https://github.com/rabbitmq/rabbitmq-java-client/blob/4b27d84456a7c9cb381002c8238d20e8db46f854/Makefile#L32-L33

Per the repo itself:
> This was migrated to https://github.com/rabbitmq/rabbitmq-server

### Reproduction steps

1. Run `make`
2. `cd deps/rabbitmq_codegen`
3. `git show remote -v` shows that the old repository is used

### Expected behavior

The `Makefile` should use the new location at https://github.com/rabbitmq/rabbitmq-server.

**Comment by michaelklishin** [comment]
While it can use that repo, I don't think `Makefile` is really used by the core team or release infrastructure. You can point `codegen.dir` to the `rabbitmq_codegen` location and Maven will pick it up.

But I have no objections to updating `Makefile` target.

**Comment by acogoluegnes** [comment]
The `Makefile` is one way to get the `rabbitmq_codegen` dependency easily (CI uses it), so I fixed it to use the directory from the broker repository.
