### ISSUE TITLE
Create enum or constants for exchange types.

### ISSUE THREAD

**Issue by flungo** [rabbitmq/rabbitmq-java-client#150]
I would like to see an enum or constants within a class for the exchange types which (as I know) are `amq.direct`, `amq.fanout`, `amq.topic`, `amq.match` and `amq.headers`.

**Comment by michaelklishin** [comment]
There can be more exchange types, so the string option is still necessary.

**Comment by flungo** [comment]
Which is why a set of constants would probably be best. It could just be a matter of preference but I would prefer to use something like `Exchange.TYPE_DIRECT`, `Exchange.Type.DIRECT` or similar. With this, it will make the set of options for the standard types almost self-documenting supporting auto-complete in an IDE (if you know where the set of type constants are stored) and reduce human error.

I am not familiar with the full code base for this project so don't know where it would be best placed otherwise I would submit a PR with the changes. If you are happy with the change to be implemented and could advise the best location for these constants, then I can implement a PR with the examples, update the use of strings throughout and add documentation for functions taking `Sting type` to refer to the constants for a list of the standard values.

**Comment by michaelklishin** [comment]
`amq.direct`, `amq.fanout` and so on are built-in exchange names, not types. The types are `direct`, `fanout`, `topic`, `headers` and plugins can provide non-standard types that begin with an `x-`.
