### ISSUE TITLE
Change history

### ISSUE THREAD

**Issue by galan** [rabbitmq/rabbitmq-java-client#152]
Is there any changelog for the rabbitmq java amqp-client? If not, you might create one. Thank you.

**Comment by michaelklishin** [comment]
rabbitmq.com/changeling.html?

**Comment by galan** [comment]
Ok thanks, I just asked myself, since in the 3.6.2 changelog of the rabbitmq has no java-client section, and there are a lot of merges going on in the branches. So it was not so obvious if something has changed for me.
