### ISSUE TITLE
Error recovering internal exchanges on reconnect

### ISSUE THREAD

**Issue by vikinghawk** [rabbitmq/rabbitmq-java-client#158]
Attempting to recover an internal exchange throws a PRECONDITION_FAILED error. Looks like RecordedExchange ignores the internal property of an exchange and assumes the default of false.

**Comment by michaelklishin** [comment]
Internal exchanges are not meant to be used by applications, so the assumption is not unreasonable.

**Comment by vikinghawk** [comment]
"If set, the exchange may not be used directly by publishers, but only when bound to other exchanges. Internal exchanges are used to construct wiring that is not visible to applications."

I assumed that to mean not visible to publishing applications, but subscribing ones were ok to create and use. I had a headers exchange in between a topic exchange and queue acting as a sort of JMS message selector. I did not want anything to publish directly to the headers exchange (publish to topic exchange only) so was using the internal property. If that is not as the feature was intended though I will switch to non-internal.
