### ISSUE TITLE
JUnit gets dragged into OSGi manifest

### ISSUE THREAD

**Issue by cfiehe** [rabbitmq/rabbitmq-java-client#162]
Since release 3.6.4 of amqp-client the following two packages get imported in the manifest header:
- junit.framework
- org.junit

The bundle cannot be resolved in an OSGi framework, because the test packages are not provided in a productive OSGi environment.

Version 3.6.3 of amqp-client does not import these two packages and gets resolved without any issues.

OSGi compatibility is a very important feature for me. Can someone please have a look what's going on during the build process.

**Comment by cfiehe** [comment]
I have posted a small Maven-based project in the RabbitMQ users group. This is the link:
https://groups.google.com/d/msg/rabbitmq-users/MsHYLoa9qEo/Sqfd6LlJBwAJ

Hopefully, it helps you to fix the problem.

**Comment by michaelklishin** [comment]
Note: to get into `3.6.x`, this depends on our build infra being fully migrated to Maven. However, it is fixed in master by @cfiehe => closing.
