### ISSUE TITLE
Make resources implement AutoCloseable

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#185]
When we drop Java 1.6 compliance.

**Comment by vikinghawk** [comment]
Do you guys have a release in mind where you would drop 1.6 support? Unfortunately my team will be stuck on 1.6 for awhile longer so just wondering when this might become an issue for us. Thanks

**Comment by michaelklishin** [comment]
When Spring does in Spring 5.

**Comment by kabl** [comment]
Why not implement Closeable? Is there since 1.5.

**Comment by acogoluegnes** [comment]
Yes, `Closeable` could also work (it's actually implemented by `Connection`), but it wouldn't for `Channel`. This issue is more of a reminder to see what we can do regarding auto-closeable resources (mainly `Connection` and `Channel`, but there may other places where it could be appropriate) when we drop Java 1.6 support.

**Comment by acogoluegnes** [comment]
Closing now #258 is done.
