### ISSUE TITLE
UnknownChannelException in AMQConnection.MainLoop.run

### ISSUE THREAD

**Issue by vikinghawk** [rabbitmq/rabbitmq-java-client#189]
Encountered this error in my ExceptionHandler.handleUnexpectedConnectionDriverException method a couple times on version 3.6.3 with connection and topology recovery enabled.

Message: RabbitExceptionHandler: Caught unexpected connection driver exception for connection XXX
Throwable: com.rabbitmq.client.impl.UnknownChannelException: Unknown channel number 147
	at com.rabbitmq.client.impl.ChannelManager.getChannel(ChannelManager.java:82)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:560)

Looks to me like there is possibility MainLoop is processing a frame with a channel number that doesn't exist in ChannelManager? Not sure how that is possible and I can't reliably reproduce... Could potentially handle this scenario in a better way though?

**Comment by acogoluegnes** [comment]
Could you provide us with a unit test that reproduces the exception? What do mean by handling this scenario in a better way? Silently ignoring the exception? Not sure it's a good idea.

BTW, also make sure your channels are accessed by only one thread at the same time, as they're not thread-safe.

**Comment by michaelklishin** [comment]
If a channel was removed from the manager when there was e.g. a delivery in flight. In some cases the best we can do is to ignore it and log a warning, I believe at least Bunny already does that.

**Comment by acogoluegnes** [comment]
OK for catching the exception and logging it.
