### ISSUE TITLE
[ERROR] from org.asynchttpclient.DefaultAsyncHttpClient in Finalizer - AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks

### ISSUE THREAD

**Issue by sripad** [rabbitmq/rabbitmq-java-client#207]
I am getting this error only after registering Rabbitmq consumer in play framework production mode
```
[ERROR] from org.asynchttpclient.DefaultAsyncHttpClient in Finalizer - AsyncHttpClient.close() hasn't been invoked, which may produce file descriptor leaks
```

**Comment by acogoluegnes** [comment]
`org.asynchttpclient.DefaultAsyncHttpClient` isn't part of the RabbitMQ Java client. You'd better off searching what's going on in Play Framework.
