### ISSUE TITLE
OSGi bundle: junit.framework should not be a required dependency

### ISSUE THREAD

**Issue by oscerd** [rabbitmq/rabbitmq-java-client#211]
From 3.6.4 the rabbitmq client OSGi bundle requires junit.framework to be installed in an OSGi container. Is this something required from the implementation or is it a bug?

**Comment by michaelklishin** [comment]
Most likely a bug. We will discuss it with the team.

**Comment by oscerd** [comment]
Thanks a lot @michaelklishin :-)

**Comment by michaelklishin** [comment]
I confirmed, it is not intentional. There is no reason to require JUnit.

**Comment by michaelklishin** [comment]
@oscerd can you please try RCs of `3.6.6` or `4.0.0`? They were announced on our mailing list, `rabbitmq-users`.

**Comment by oscerd** [comment]
Sure :-)

**Comment by michaelklishin** [comment]
To make things easier to find, `3.6.x` preview releases are available [from GitHub as part of RabbitMQ distribution releases](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_6_rc1). `4.0.0` previews are published as Maven artifacts only.

**Comment by oscerd** [comment]
@michaelklishin it works fine with 3.6.6-SNAPSHOT. So we'll wait for the release :-)

**Comment by acogoluegnes** [comment]
For 4.0.0, you can grab the latest RC here (*Files* tab): https://bintray.com/rabbitmq/maven-milestones/java-client/4.0.0.RC1#files/com/rabbitmq/amqp-client/4.0.0.RC1

I checked both 3.6.6 and 4.0.0 latest RCs and JUnit doesn't appear in the manifest. We changed parts of the build system, so errors may have sneaked in.

**Comment by oscerd** [comment]
@acogoluegnes Thanks. I can confirm 3.6.6-SNAPSHOT works fine. Sorry for the noise.

**Comment by oscerd** [comment]
I guess we can close the issue :-)

**Comment by michaelklishin** [comment]
Tagging this as resolved in `3.6.6`.

**Comment by oscerd** [comment]
Thanks guys.
