### ISSUE TITLE
Remove usage of QueueingConsumer in tests

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#213]
`QueueingConsumer` has been deprecated in 4.0.0, all tests relying on it should use an alternative.

**Comment by michaelklishin** [comment]
Good idea.

**Comment by acogoluegnes** [comment]
Many tests use `QueueingConsumer` and a refactoring wouldn't bring much, so there's now a `QueueingConsumer` class in the test directory. I won't ship with the client binary.
