### ISSUE TITLE
AutorecoveringChannel throws NullPointerException during network outages

### ISSUE THREAD

**Issue by abhijeetkushe** [rabbitmq/rabbitmq-java-client#216]
While testing application resiliency (through tweaking iptables, toxi-proxy and brute force way (removing the plug)) we discovered the AutorecoveringChannel throws nullpointerexception possibly because inner delegate is null.This cannot be reproduced via a deterministic set of steps.You can try a combination of  above 3 approaches a x number of times and expect this to happen. rabbitmq client version 3.5.5
```
java.lang.NullPointerException
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.isOpen(AutorecoveringChannel.java:461)
        at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$CachedChannelInvocationHandler.invoke(CachingConnectionFactory.java:655)
        at com.sun.proxy.$Proxy109.basicGet(Unknown Source)
        at 
```

**Comment by michaelklishin** [comment]
You use Spring AMQP which performs caching on objects. Please find a way to reproduce without it and open another issue if you can. There is a brief time window in which `delegate` is not a "functional" channel, although it should not be `null`.

**Comment by abhijeetkushe** [comment]
I can try to reproduce it but do you recommend not using Spring AMQP's CachingConnectionFactory ?

**Comment by michaelklishin** [comment]
I don't think you have a choice. Our team does not maintain Spring AMQP so we need a way to reproduce with just this client. Oh, and please specify the versions used in the future.

**Comment by michaelklishin** [comment]
I see that you have mentioned a version in the last sentence. Please test against `3.6.5` and `4.0.0.RC2`. There will be no more `3.5.x` releases of the client (technically there will be one but it will be identical to `3.5.7`.

**Comment by michaelklishin** [comment]
In fact, testing against [`3.6.6.RC2`](https://github.com/rabbitmq/rabbitmq-server/releases/tag/rabbitmq_v3_6_6_rc2) can be an even better idea than `3.6.5` at this point. `3.6.6` can ship any day now :)

**Comment by madhavajay** [comment]
3.6.6 RC was fixed reconnection issues for me!!!
