### ISSUE TITLE
Consider Adding toString() to AutorecoveringChannel

### ISSUE THREAD

**Issue by garyrussell** [rabbitmq/rabbitmq-java-client#217]
Logging `Recoverable` in the `RecoveryListener` emits...

    Channel recovery complete: com.rabbitmq.client.impl.recovery.AutorecoveringChannel@3571b748

Consider adding something like:

    @Override
    public String toString() {
        return "AutorecoveringChannel:" + delegate;
    }

Workaround:

    ((AutorecoveringChannel) recoverable).getDelegate().toString();

**Comment by michaelklishin** [comment]
Makes sense. Would you like to submit a PR? :)

**Comment by garyrussell** [comment]
Will do
