### ISSUE TITLE
Consider changing default trust manager

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-java-client#229]
See #226, #227, #228.

This is a breaking change with potentially serious ramifications for beginners or those not familiar with TLS and certificate management. On the other hand, it does make TLS actually effective by default. Note: [RabbitMQ TLS guide](http://www.rabbitmq.com/ssl.html) already provides an example that uses peer verification. It has been the case for years.

So this should be considered carefully.

**Comment by acogoluegnes** [comment]
I don't think changing a default behavior that has been there for years is a good idea. We already added an explicit warning with #230 and there's a very thorough TLS guide in the documentation. We can improve the Javadoc of some of the `ConnectionFactory#useSslProtocol` methods to make explicit the connections will trust every server and also add a quick section in the Java Client API guide (default is to trust all servers and add a link to the TLS guide, as there's no mention of TLS in the Java Client API guide right now).

@michaelklishin WDYT?

**Comment by michaelklishin** [comment]
@acogoluegnes we can add a brief Java-specific section about TLS and peer verification to the docs and close this. I'm very much on the fence about changing this default because

 * It has been around for so long
 * Without it, many developers will immediately run into peer verification issues without understanding anything about TLS, x509 or chain verification
 * Most developers ignore warnings unless things break
 * It is, of course, not a secure default

**Comment by acogoluegnes** [comment]
@michaelklishin Sounds good.
