### ISSUE TITLE
Deprecate `NullTrustManager`

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#234]
Just a matter of name, create a `AlwaysTrustTrustManager` clone, and remove `NullTrustManager` in 5.0.

See #230.

**Comment by michaelklishin** [comment]
How about `TrustEverythingTrustManager` or `MostNaiveTrustManager`?

**Comment by acogoluegnes** [comment]
I prefer my `AlwaysTrustTrustManager` over `TrustEverythingTrustManager`, but I admit the 2 `Trust`s in a row don't make it very readable.
I like `MostNaiveTrustManager` (it's so naive, it lets everyone pass), but it's not immediately obvious that it trusts everyone.
Let's go with `TrustEverythingTrustManager`.

**Comment by michaelklishin** [comment]
OK, I'm fine with that.

**Comment by mhewedy** [comment]
I wanted to have a proper name for my "trust all TM", and I come up with NullTrustManager (in the same way as /dev/null)

But I find you changed the name, and then I liked `TrustEverythingTrustManager` except that it is a very long name.
