### ISSUE TITLE
Replace AssertionErrors with RuntimeExceptions

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#239]
Use e.g. `IllegalStateException` instead of `AssertionError` in `BlockingCell` and other part of the code (when appropriate). The `Error` family is too dramatic for this class and client code that tries to handle exceptions from `BlockingCell` could end up dealing with cases it cannot recover from anyway.

Related to #237.

Reverse also the changes from #237, so the NIO loop doesn't actually handle `AssertionError` coming from elsewhere than `BlockingCell`.

**Comment by acogoluegnes** [comment]
See suggestions from @dimas:
https://github.com/rabbitmq/rabbitmq-java-client/issues/237#issuecomment-272987360
https://github.com/rabbitmq/rabbitmq-java-client/issues/237#issuecomment-272987782

**Comment by vikinghawk** [comment]
Looks like there are still some instances of Error's in the code base such as UnexpectedFrameError, UnexpectedMethodError, and some places that throw a generic Error. Any chance those places could be switched to RuntimeExceptions too? For example there are a couple places that catch UnsupportedEncodingExceptions and wrap them in an Error. The code could be updated to use Charset.forName() which throws a runtime UnsupportedCharsetException.

**Comment by michaelklishin** [comment]
@vikinghawk we would definitely consider that for 5.0. Feel free to submit a PR against master.

**Comment by acogoluegnes** [comment]
Fixed by 3c010f724cb22a7366fa3b305ff8d97e29617ec9. Thanks @vikinghawk !
