### ISSUE TITLE
Make SslContext creation more flexible

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#241]
E.g. allow to have a `SslContext` created for each connection of the same `ConnectionFactory`.

See https://groups.google.com/d/msg/rabbitmq-users/Jl5ffHgueDw/1bUsPxzYEAAJ.

**Comment by acogoluegnes** [comment]
This would typically require API changes, e.g. in `FrameHandlerFactory`.

**Comment by vibhuyadav** [comment]
This would be a great addition
