### ISSUE TITLE
Consider a stream-oriented way to consume messages

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-java-client#249]
Now that we can require JDK 8 in master, we can explore a way to expose a stream of deliveries as a `Stream<T>`.

There is some overlap with [Reactor](https://projectreactor.io/) support so maybe this issue should be dropped in favour of that, however, not every system uses Reactor. So the scope of this needs to be narrowed down first, which is TBD.

**Comment by acogoluegnes** [comment]
After some experimentation with `Stream`, we decided this API wasn't appropriate to handle an asynchronous listener as a stream of messages. A better option is to Reactor's `Flux`.
