### ISSUE TITLE
Incorrect reason in ShutdownSignalException

### ISSUE THREAD

**Issue by uvzubovs** [rabbitmq/rabbitmq-java-client#253]
Please take a look at the attached snapshot. Class id and method id are printing as zeros, and member vars are zeros, but when protocolClassId() returns 10 and method id returns 50.

![reason](https://cloud.githubusercontent.com/assets/16563442/23518030/fcf7eb66-ff26-11e6-8104-17a812859d87.JPG)

**Comment by michaelklishin** [comment]
What tool is that?

**Comment by uvzubovs** [comment]
Eclipse

**Comment by michaelklishin** [comment]
May I ask you to reproduce with 3.6.6 or 4.1.0? You can use those versions on JDK 6 against RabbitMQ 3.5.x or 3.6.x or even master, by the way.

**Comment by acogoluegnes** [comment]
`protocolClassId()`/`protocolMethodId()` and `getClassId()`/`getMethodId()` are 2 differents sets of methods.
`protocolClassId()`/`protocolMethodId()` are the AMQP identifiers of the method (class ID = 10 for `connection`, method ID = 50 for `close`). Those 2 methods are common to all AMQP `Method` of the Java Client.
`getClassId()`/`getMethodId()` are specific to `connection.close`. From the specification: 
> `class­id`: failing method class. When the close is provoked by a method exception, this is the class of the method.
> `method­id`: failing method ID. When the close is provoked by a method exception, this is the ID of the method.

Those last two are set to 0 as the connection is closed from the management UI, no AMQP method is to be blamed for the closing.
