### ISSUE TITLE
Implement AutoCloseable in Channel

### ISSUE THREAD

**Issue by Banananan** [rabbitmq/rabbitmq-java-client#258]
It would be nice to implement `AutoCloseable` interface in `Channel` class and override its' `close` method.
`AutoCloseable` implementation was previously done in https://github.com/rabbitmq/rabbitmq-java-client/issues/131 in `Connection` class but `Channel` was left with a comment "I wanted to add it to Channel-class also but it had a checked exception TimedOutException that broke the contract of Closeable so I avoided it." (https://github.com/rabbitmq/rabbitmq-java-client/pull/133) but there is no specification for `close` method to not throw `java.util.concurrent.TimeoutException`. `close` method should not throw `java.lang.InterruptedException`.

**Comment by michaelklishin** [comment]
The docs [seem to concur](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html). Now that we are working on 5.0 targeting JDK 8, we can reconsider this.

**Comment by zaharidichev** [comment]
Can i have a take on that one ?

**Comment by michaelklishin** [comment]
@zaharidichev sure, why not. Take a look at [CONTRIBUTING.md](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/CONTRIBUTING.md). I believe this change is small enough to not require a signed CA but if you could file on, it'd be particularly appreciated. Thank you!
