### ISSUE TITLE
metrics for closing connections

### ISSUE THREAD

**Issue by Paxa** [rabbitmq/rabbitmq-java-client#259]
I'm trying to make some logging to see when connection is open, message pushed and connection is closed

My code is:

```java
factory = new ConnectionFactory();
factory.setAutomaticRecoveryEnabled(true);
factory.setTopologyRecoveryEnabled(false);
factory.setExceptionHandler(new QueueExceptionHandler());

MyMetricsCollector metrics = new MyMetricsCollector();
factory.setMetricsCollector(metrics);

Connection connection = factory().newConnection(getAddresses());
logger.info("Connected {} {}", connection, connection.getClass());
Channel channel = connection.createChannel();
logger.info("Pushing to RabbitMQ: queue: {} message: {}", queueName, message);
channel.basicPublish("", queueName, messageProps(), message.getBytes());
channel.close();
connection.close(5);
logger.info("Done");

...

public static class MyMetricsCollector extends NoOpMetricsCollector {
    static final Logger logger = LoggerFactory.getLogger(MyMetricsCollector.class);

    @Override
    public void newConnection(Connection connection) {
        logger.info("newConnection");
    }

    @Override
    public void closeConnection(Connection connection) {
        logger.info("closeConnection");
    }

    @Override
    public void newChannel(Channel channel) {
        logger.info("newChannel");
    }

    @Override
    public void closeChannel(Channel channel)  {
        logger.info("closeChannel");
    }

    @Override
    public void basicPublish(Channel channel) {
        logger.info("closeChannel");
    }
}
```

Output:
```
newConnection
Connected amqp://guest@127.0.0.1:5672/ class com.rabbitmq.client.impl.recovery.AutorecoveringConnection
newChannel
Pushing to RabbitMQ: queue: my_queue message: {"id": 1223}
basicPublish
Done
```

I expect to see `closeChannel` and `closeConnection` messages, but that method not called. And there is no exceptions thrown.

How to get metrics work?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes we have a certain amount of information to work with. Questions, investigations, root cause analysis, discussions for potential features are all considered to be mailing list material by our team. When/if we have enough details and evidence we'd be happy to file a new issue.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users). Thank you.

**Comment by Paxa** [comment]
Are you sure that mailing list is working?
May be you can take a look some time? https://groups.google.com/forum/#!topic/rabbitmq-users/Y-jRR2VyYgs

**Comment by michaelklishin** [comment]
@Paxa the list is getting dozens of emails every day, so it must be pretty functional. You are not guaranteed a response just because you posted, though.

The person who primarily maintains this client is on medical leave. If this matter is urgent to you, look at the code and do your own debugging.

**Comment by Paxa** [comment]
thank you for your reply, it can wait

**Comment by kjnilsson** [comment]
@Paxa I've replied to your mailing list thread with a suggestion.
