### ISSUE TITLE
RPC too slow

### ISSUE THREAD

**Issue by tvd12** [rabbitmq/rabbitmq-java-client#263]
I use ```RpcClient``` and ```RpcServer``` and loop 1000 time (very simple message), it spent 905 milliseconds

My environment: 

amqp-client-4.1.0
MacBook Pro (Retina, 13-inch, Late 2013)
Processor 2.4 GHz Intel Core i5
Memory 8 GB 1600 MHz DDR3

**Comment by michaelklishin** [comment]
Those classes are examples. They involve a round trip plus a queue declaration for every message. It can be avoided using Direct Reply-to and batching of requests.

**Comment by tvd12** [comment]
no, 
I use RpcClient, RpcServer of version 4.1.0
I declare a queue one time and use many time
I use 'reply-to' : amq.rabbitmq.reply-to
but it's too slow

**Comment by michaelklishin** [comment]
@tvd12 this is not a support forum. I've explained above that those classes are examples and they intentionally wait for a response. Publishing and consumption is inherently asynchronous in this client and the protocol. Nothing prevents you from building a completely asynchronous implementation of the request/response pattern.

Of course, I don't know if that would not be "too slow" or not but there's only one way to find out.
