### ISSUE TITLE
Autorecovery does not to recover consumers which have the same consumer tag

### ISSUE THREAD

**Issue by bkittelmann** [rabbitmq/rabbitmq-java-client#285]
According to the [RabbitMQ documentation](https://www.rabbitmq.com/api-guide.html#consuming) it is valid to have consumers with the same tag, as long as they are on different channels. But the channels can belong to the same connection. 

> When calling the API methods relating to Consumers, individual subscriptions are always referred to by their consumer tags, which can be either client- or server-generated as explained in the AMQP specification document. Distinct Consumers on the same Channel must have distinct consumer tags. 

We discovered recently that autorecovery does not recover all consumers. For those that have the same tag, it will only recover one. There is no error logged nor any exception throw.

I think the explanation for this behaviour is how the consumers are recorded by `AutorecoveringConnection` and `AutorecoveringChannel`. `AutorecoveringConnection.consumers` is a map in which the consumer references are stored as values, with their tags as keys. In `AutorecoveringChannel.basicConsume` the result from `AutorecoveringChannel.basicConsume` is used as the key, and passed into `AutorecoveringChannel.recordConsumer`.

```java
public String basicConsume(String queue, boolean autoAck, String consumerTag, boolean noLocal, boolean exclusive, Map<String, Object> arguments, Consumer callback) throws IOException {
    final String result = delegate.basicConsume(queue, autoAck, consumerTag, noLocal, exclusive, arguments, callback);
    recordConsumer(result, queue, autoAck, exclusive, arguments, callback);
    return result;
}
```

`AutorecoveringChannel.recordConsumer` then uses the `result` string as the key to store the consumer reference in the map used by the connection. If you have multiple consumers with the same tag in distinct channels, the last one recorded will be the only one remaining in the map of the connection.

```java
private void recordConsumer(String result,
                            String queue,
                            boolean autoAck,
                            boolean exclusive,
                            Map<String, Object> arguments,
                            Consumer callback) {
    RecordedConsumer consumer = new RecordedConsumer(this, queue).
                                        autoAck(autoAck).
                                        consumerTag(result).
                                        exclusive(exclusive).
                                        arguments(arguments).
                                        consumer(callback);
    this.consumerTags.add(result);
    this.connection.recordConsumer(result, consumer);
}
```

One solution could be to make the keys used as tags unique by prefixing them with a value distinct for each channel. This change for `basicConsume` should demonstrate the approach, I haven't researched though if the channel number is a good candidate to use for this purpose.

```java
final String recordedTag = getChannelNumber() + "-" + result;
recordConsumer(recordedTag, queue, autoAck, exclusive, arguments, callback);
```

Naturally, if one relies on server-generated tags, this issue never presents itself.

**Comment by michaelklishin** [comment]
Sorry but I don't think it's an issue worth fixing. Using identical consumer tags will cause confusion in other situations.

**Comment by michaelklishin** [comment]
I updated the docs to explicitly recommend against reused consumer tags.

**Comment by Shadowfiend** [comment]
Disclaimer: I'm on the same team that got bit by this issue @bkittelmann reported. 

That said, as a humble spec/documentation reader, there is a seemingly large difference between ‘reusing consumer tags will cause confusion and is not recommended’ and ‘reusing consumer tags will cause autorecovery to fail to recover consumers with duplicate tags’. One implies (to me) that it could cause confusion to humans, while the other states that there will be expected system behavior that will not occur.

This is particularly true when the documentation implies that distinct consumer tags on *different* channels are supported (‘[d]istinct Consumer instances on the same Channel must have distinct consumer tags’) in conjunction with the AMQP spec's *explicitly* saying ‘[t]he consumer tag is local to a channel, so two clients can use the same consumer tags’.

So I would suggest the language here should be clarified to state that in addition to consumer tag reuse not being recommended, the Java client specifically does not support consumer tag reuse in conjunction with autorecovery. I'm happy to provide a pull request to do this if that is deemed the right thing to do and eases the burden on the maintainers (and assuming [this file](https://github.com/rabbitmq/rabbitmq-website/blob/master/site/api-guide.xml) is the one to PR).

**Comment by michaelklishin** [comment]
In case it's not clear to someone landing here from Google what is going on under the hood.

Consumers are scoped per channel, which means technically you can reuse an identifier between channels. However, connection recovery cache is per connection for a reason: you don't want to run into the following scenario:

 * Declare something on channel A
 * Delete it on channel B
 * See it re-appear after recovery

Spec authors could not foresee this as automatic connection recovery — or any recovery strategy — is entirely a client library implementation detail.

**Comment by michaelklishin** [comment]
@Shadowfiend I will make the warning more alarming but we can't list every single consequence of using duplicate consumer tags. Consumer tag is a consumer identifier. Using duplicate identifiers sounds like a never ending source of confusion to me, for example, when consumers are monitored. Should we also document that in the Java client guide? I don't think so.

**Comment by Shadowfiend** [comment]
I understand what you're saying, absolutely. I think if the docs said something like “Distinct consumer instances on the same channel must have distinct consumer tags, but reusing consumer tags across channels can still lead to unexpected behavior in the system. Reusing consumer tags in any way is strongly discouraged.” (or something close to that) would make it clear that the concern is not solely confusion, but the potential for actual system issues.

Hope that makes sense---not sure if I'm drawing a strange distinction. Regardless of wording, I think a stronger warning would be excellent.

**Comment by michaelklishin** [comment]
@Shadowfiend deployed a stronger warning live, please take a look.

**Comment by bkittelmann** [comment]
It's fine with me to make it explicit in the docs that duplicate identifiers are not supported.

To give a bit of context, there was a reason we had duplicate identifiers. We used the consumer tag to communicate extra meta-information about the consumer. In our system, clients connect through an AWS ELB to our RabbitMQ cluster. When we look in the RabbitMQ web console to see who's consuming on which queue, we could not associate the IP addresses listed to anything of the client servers as they are IPs from the ELB. But if we set a consumer tag like "$componentName-$ipAddress" we could easily make this information show up in the web console. And as we had multiple consumers per server, sharing the same connection, we ran into the issue discussed here after recovery.

Our current workaround is to have "$componentName-$ipAddress-$randomSuffix" as consumer tag and that seems to work ok for now.

**Comment by michaelklishin** [comment]
@bkittelmann are you aware of `ConnectionFactory#newConnection` overrides that include a user-provided connection name?

I think a random suffix is a good solution in this case.

**Comment by bkittelmann** [comment]
> are you aware of ConnectionFactory#newConnection overrides that include a user-provided connection name?

I was not - thanks for the pointer. That could be a good alternative for our use case.

**Comment by michaelklishin** [comment]
OK. That's a relatively new thing (added in `3.6.3` IIRC). The name is displayed on a couple of pages in the management UI plus some log entries.
