### ISSUE TITLE
org.hamcrest.Matchers is not available

### ISSUE THREAD

**Issue by rapgro** [rabbitmq/rabbitmq-java-client#294]
rabbitmq-java-client 4.1.1, OpenJDK 1.8, Fedora 26, hamcrest 1.3

```
[ERROR] /home/builder/fedora-scm/rabbitmq-java-client/rabbitmq-java-client-4.1.1/src/test/java/com/rabbitmq/client/test/ChannelRpcTimeoutIntegrationTest.java:[30,27] cannot find symbol
  symbol:   class Matchers
  location: package org.hamcrest
```

and other code lines as well with the same error.

**Comment by michaelklishin** [comment]
I cannot reproduce this in several environments with JDK 8u102 and 8u131. I'm afraid our small team does not have the resources to investigate building from source issues in 4.1.x specific to a particular available JDK version.

**Comment by rapgro** [comment]
Sorry, but it does not work on Fedora 26. Could you try to build in an updated system as I said? Maybe the hamcrest package in Fedora misses something or is patched to not provide the Matchers class, I don't know.

**Comment by michaelklishin** [comment]
OK I think I understand what the issue is. [org.hamcrest.Matchers](https://github.com/hamcrest/JavaHamcrest/blob/2efed149d006249d607e3b3463366031b0f6ac80/hamcrest-library/src/main/java/org/hamcrest/Matchers.java) is a part of `hamcrest-library`, not core.

**Comment by michaelklishin** [comment]
@rapgro I pushed `try-rabbitmq-java-client-294` which adds a dependency on `hamcrest-library` for tests. Please give it a try.
