### ISSUE TITLE
basicConsume with no-local flag not working as intended

### ISSUE THREAD

**Issue by jcoeltjen** [rabbitmq/rabbitmq-java-client#303]
When doing a channel.basicConsume() with the no-local flag set, no messages published by this connection should arrive in handleDelivery() of the Consumer.

But is seems that the flag is ignored as it does not make any difference if I set or unset it.

Affected versions: 4.2.0 and 4.2.1 (tested, maybe more)

Minimal example: 

```java
import com.rabbitmq.client.*;

import java.io.IOException;
import java.nio.charset.StandardCharsets;

public class NoLocal {

    public static void main(String[] args) throws Exception {

        ConnectionFactory connectionFactory = new ConnectionFactory();
        Connection connection = connectionFactory.newConnection();
        Channel channel = connection.createChannel();

        channel.exchangeDeclare("test-e", BuiltinExchangeType.FANOUT, false, true, null);
        channel.queueDeclare("test-q", false, false, true, null);
        channel.queueBind("test-q", "test-e", "test-r");

        channel.basicConsume("test-q", true, "consumer-tag", true, false, null, new DefaultConsumer(channel) {
            @Override
            public void handleDelivery(String consumerTag, Envelope envelope, AMQP.BasicProperties properties, byte[] body) throws IOException {
                System.out.println("should not print this at all ");
                System.out.println("message: " + new String(body, StandardCharsets.UTF_8));
            }
        });

        channel.basicPublish("test-e", "test-r", null, "message".getBytes(StandardCharsets.UTF_8));

        Thread.sleep(5000);
    }
}
```

In my understanding the prints in the handleDelivery() method of the consumer should not be called as the noLocal flag if the basicConsume is set to true.

**Comment by sigiesec** [comment]
This is a restriction of the rabbitmq-server, not the rabbitmq-java-client, as described at https://www.rabbitmq.com/specification.html:
> The no-local parameter is not implemented. The value of this parameter is ignored and no attempt is made to prevent a consumer from receiving messages that were published on the same connection.
