### ISSUE TITLE
RpcClient.java get NullPointerException

### ISSUE THREAD

**Issue by tvd12** [rabbitmq/rabbitmq-java-client#306]
In RpcClient.java we have:

```java
          @Override
            public void handleDelivery(String consumerTag,
                                       Envelope envelope,
                                       AMQP.BasicProperties properties,
                                       byte[] body)
                    throws IOException {
                synchronized (_continuationMap) {
                    String replyId = properties.getCorrelationId();
                    BlockingCell<Object> blocker = _continuationMap.get(replyId);
                    _continuationMap.remove(replyId);
                    blocker.set(new Response(consumerTag, envelope, properties, body));
                }
            }
```
Because, we haven't checked ```blocker != null```, so we get NullPointerException
And
Why we don't use:

```java
 BlockingCell<Object> blocker = _continuationMap.remove(replyId);
```
instead of

```java
BlockingCell<Object> blocker = _continuationMap.get(replyId);
                    _continuationMap.remove(replyId);
```

**Comment by acogoluegnes** [comment]
@tvd12 Can you provide a code snippet that reliably reproduce the `NullPointerException`? I don't mind making the code more defensive, but I'd like to do it for a reason.

**Comment by tvd12** [comment]
I have seen NullPointerException when RpcServer received two request with duplicate correlationId from client. It's a mistake from me, but I think anyone are easy to make that mistake, anh if we throw an exception with detail message, it's a help for many developers.
Sorry, I fixed a lot of source code and now I don't want rollback them, so I can't provide to you.
