### ISSUE TITLE
nextDelivery method returning null

### ISSUE THREAD

**Issue by jiangfuqiang** [rabbitmq/rabbitmq-java-client#31]
The nextDelivery method is returning null all the time after my program run about an hour every time.I don't know what happened.I am just think that the LinkedBlockingQueue is empty after some time and not filled with another. 
My program is running with three threads in a thread pool and sharing a connection but the channel is independent. I am waiting for your response please.

**Comment by michaelklishin** [comment]
Please direct your questions to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).
