### ISSUE TITLE
property file-based initialization

### ISSUE THREAD

**Issue by rabbit-hunter** [rabbitmq/rabbitmq-java-client#324]
This is a feature request for the RabbitMQ Java library.

It would be useful if we could initialize the `ConnectionFactory` via a properties file. Now, whenever we want to set a new configuration property, we have to change the code to call the setter. It would be more convenient if we just could alter the properties file.

You could take Hikari as an example, see https://github.com/brettwooldridge/HikariCP#initialization. A java.util.properties file can be provided. Whenever we want to alter the configuration, we just update the properties file, without being forced to alter the code.

```
// Examines both filesystem and classpath for .properties file
HikariConfig config = new HikariConfig("/some/path/hikari.properties");
HikariDataSource ds = new HikariDataSource(config);
```

**Comment by michaelklishin** [comment]
This can work for a limited number of (common) settings. I'm not sure what can be done about e.g. collections — should command separated lines be used?

And some values, e.g. a `SocketConfigurator`, would not be supported by this.

@acogoluegnes WDYT?

**Comment by acogoluegnes** [comment]
@michaelklishin Seems to me like a good idea. Like you said, we won't be able to support all the options (e.g. `SocketConfigurator`, `ExceptionHandler`) and have to use some conventions (e.g. comma-separated for URLs), but overall it should be straightforward.

**Comment by rrrrrrrrramba** [comment]
+1 for this, this would be very useful

**Comment by rrrrrrrrramba** [comment]
I will try to verify this in the next days.

**Comment by rrrrrrrrramba** [comment]
I did a quick test with 4.4.0-SNAPSHOT as of today.

I replaced following working code:

```
        final ConnectionFactory f = new ConnectionFactory();

        try {
            f.setUri("amqp://user:password@localhost:5672/vhost");
        } catch (Exception) {
            e.printStackTrace();
        }
        return f.newConnection();
```

by

```
        final ConnectionFactory f = new ConnectionFactory();
        final Properties p = new Properties();

        p.setProperty("uri", "amqp://user:password@localhost:5672/vhost");
        f.load(p);

        return f.newConnection();
```

Now I am getting:

`java.net.ConnectException: Connection refused (Connection refused)`

I did not do any further analysis so far.

Any idea?

Sidenote, it would be cool if these functions supported a fluent style:

    return new ConnectionFactory().load(p).newConnection();

**Comment by rrrrrrrrramba** [comment]
Please ignore previous comment. I did not see that there was a default prefix. Now, when setting `rabbitmq.uri` instead of `uri`, it works!

**Comment by rrrrrrrrramba** [comment]
@michaelklishin I wasn't providing an uri, see previous comment. So it was probably falling back to some default credentials, which aren't allowed on my host (standard 3.6.x Docker image).

**Comment by rrrrrrrrramba** [comment]
@acogoluegnes FYI, I finished my tests, based on commit `cb03deefea17364ed5d5631666734dc00142aae5` and it all seems to work fine!

**Comment by rrrrrrrrramba** [comment]
Will this also be merged in the 5.x master branch?

**Comment by rrrrrrrrramba** [comment]
Great!
