### ISSUE TITLE
ConnectionFactory: fluent style

### ISSUE THREAD

**Issue by rrrrrrrrramba** [rabbitmq/rabbitmq-java-client#330]
It would be useful if the API of `ConnectionFactory` supported fluent style. For example:

    Connection c = new ConnectionFactory().setUri(...).newConnection();
    Connection c = new ConnectionFactory().load(...).newConnection();

Most of the times, this involves returning `this` in the setters.

I know this might be a personal opinion, but what do you think?

**Comment by acogoluegnes** [comment]
Good idea. `NioParams`, introduced in 4.0, already uses a fluent API. This is a breaking change though, so it must be introduced in the next major release, that is 6.0.

**Comment by rrrrrrrrramba** [comment]
Great, thanks!

**Comment by enniokerber** [comment]
Hey @acogoluegnes,

I feel like this might be a topic suited for an Open-Source beginner. Would you mind assigning this to me? I'd be eager to work on it.

Greetings,
Ennio

**Comment by michaelklishin** [comment]
Thanks for contributing, @enniokerber. @acogoluegnes perhaps we can ship a small (source-level) backwards compatible like #1038 in `5.18`?

**Comment by acogoluegnes** [comment]
#1038 is not exactly a backward-compatible change: applications or libraries using reflection could depend on the method return type. This is very unlikely though, so I'd say we can backport this to 5.x. Is that OK with you @michaelklishin?
