### ISSUE TITLE
Fix client version property file name

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#335]
The file isn't correctly named: `rabbitmq-ampq-client.properties` instead of `rabbitmq-amqp-client.properties`.

**Comment by guidomedina** [comment]
@acogoluegnes is there a plan to release a `5.5.1` for this issue too? I see only `4.4.1` was released.

**Comment by michaelklishin** [comment]
There is.

**Comment by acogoluegnes** [comment]
@guidomedina 5.1.1 is now available on Maven Central.

**Comment by guidomedina** [comment]
Many thanks, nice job.
