### ISSUE TITLE
Metrics for unsuccessful outgoing publishes

### ISSUE THREAD

**Issue by slayful** [rabbitmq/rabbitmq-java-client#354]
Hey there! This is a feature request I'd be willing to create PR for.

As it stands now, when you're publishing a message and it is successful, the `published` counter in [MetricsCollector](https://github.com/rabbitmq/rabbitmq-java-client/blob/master/src/main/java/com/rabbitmq/client/MetricsCollector.java) will be incremented.
I'd like to add `publishFailed` counter, which will be incremented if and when publishing attempt fails.

This will allow users to easily create reports of publishing success rates and help them determine if the number messages they're not publishing are a significant enough to increase resiliency of their programs.

 I'd like to find out if this is a feature that would be a welcome addition and if the way I'd like to add it would meet your expectations.

**Comment by michaelklishin** [comment]
Unfortunately it's not obvious [how to know if a publishing attempt failed](http://www.rabbitmq.com/heartbeats.html). Not all failures result in timely I/O exceptions.

**Comment by michaelklishin** [comment]
@acogoluegnes we can count (I/O and other) exceptions on publish attempts and negative [publisher acknowledgements](http://www.rabbitmq.com/confirms.html). This would not account for publishes that technically were written to the socket but were never acknowledged because connection went down right after. WDYT?

Having two categories is a better idea than lumping everything together, given that there's at least one other category which it or may not be possible to reliably count.

**Comment by michaelklishin** [comment]
Another question is whether returned (uncountable) messages should count for "unsuccessful". Again, I think it should be a separate category.

**Comment by acogoluegnes** [comment]
Sounds reasonable to me. If we sum up:
 * publish attempts (failures/exceptions in `basicPublish`)
 * publisher confirms (`ConfirmListener#handleAck`)
 * failed publisher confirms (`ConfirmListener#handleNack`)
 * failed deliveries (`ReturnListener#handleReturn`)

We may add new methods to `MetricsCollector`, but then the change would need to go into 6.0.0. We may also create a new interface, e.g. `PublishingMetricsCollector` that the current collector implementations would implement and release this in the 5.x branch as there would be no breaking changes (not really sure about that actually, but it's worth investigating). With the latter, the metrics collecting logic may be tricky, as we would need to juggle with new interfaces.

**Comment by michaelklishin** [comment]
I took the liberty to edit @acogoluegnes' comment to clarify some proposed metric names.

**Comment by slayful** [comment]
@michaelklishin, @acogoluegnes I've implemented the first and most basic type of failure, would you mind giving it a look?
I was thinking that after addressing the CR for ths PR, we could merge it and I could add the other types in other PRs to keep them on the smaller side, how's that sound?

**Comment by michaelklishin** [comment]
@slayful thank you, we will next week. It just so happens that both Java client maintainers on the core team are on PTO this week. Having follow-up PRs with other improvements (even if they depend on this one) is what we'd prefer.

**Comment by slayful** [comment]
Thanks @michaelklishin! :)

**Comment by slayful** [comment]
Seems like we could merge https://github.com/rabbitmq/rabbitmq-java-client/pull/357 and I could add the other types of failures.

**Comment by slayful** [comment]
https://github.com/rabbitmq/rabbitmq-java-client/pull/360 is ready for a second review. :)

**Comment by michaelklishin** [comment]
@slayful thank you!

**Comment by slayful** [comment]
Thank you for merging and helping me do this. We'd love to start monitoring our publishing rates, so please don't mind me asking, do you have an idea when will it be part of a release?

**Comment by michaelklishin** [comment]
Release plans for 6.0 haven't been discussed yet but I think a month or so is realistic. We certainly can release a milestone some time this week.

**Comment by acogoluegnes** [comment]
We can indeed release a milestone in the next few days. We still have a [few things to address in 6.0](https://github.com/rabbitmq/rabbitmq-java-client/milestone/40).

**Comment by acogoluegnes** [comment]
Note I created a [follow-up issue](https://github.com/rabbitmq/rabbitmq-java-client/issues/372) to handle multiple publisher confirms in metrics.

**Comment by acogoluegnes** [comment]
@slayful 6.0.0.M1 is out: https://groups.google.com/d/msg/rabbitmq-users/yGsBB8Rom2w/leIkIwv7AgAJ

**Comment by slayful** [comment]
Thanks! :)
