### ISSUE TITLE
Documentation for running tests might be incorrect or not up to date

### ISSUE THREAD

**Issue by slayful** [rabbitmq/rabbitmq-java-client#359]
Despite running `make deps` in `rabbitmq-java-client` I've faced issues when running tests on my local setup. I kept getting an issue related with tls-certs:
```
INFO] --- groovy-maven-plugin:2.0:execute (query-test-tls-certs-dir) @ amqp-client ---
GEN    /var/folders/z7/5fjfgbg52rldk6_8vn58l2d00000gp/T//rabbitmq-test-instances/tls-certsmake: *** /Users/sly/code/rabbitmq-java-client/deps/rabbitmq_ct_helpers/tools/tls-certs: No such file or directory.  Stop.make[1]: *** [/var/folders/z7/5fjfgbg52rldk6_8vn58l2d00000gp/T//rabbitmq-test-instances/tls-certs] Error 2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.407 s
[INFO] Finished at: 2018-04-23T15:10:38+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.gmaven:groovy-maven-plugin:2.0:execute (query-test-tls-certs-dir) on project amqp-client: Execution query-test-tls-certs-dir of goal org.codehaus.gmaven:groovy-maven-plugin:2.0:execute failed: org.apache.maven.plugin.MojoExecutionException: Failed to query test TLS certs directory with command: make -C /Users/sly/code/rabbitmq-java-client/deps/rabbit --no-print-directory show-test-tls-certs-dir DEPS_DIR=/Users/sly/code/rabbitmq-java-client/deps -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
gmake: *** [Makefile:30: tests] Error 1
```

I had to:
* alias make to gmake `alias make=gmake`, but I probably could have just run all commands with `MAKE=gmake`
* `git clone https://github.com/rabbitmq/rabbitmq-ct-helpers` into `rabbitmq-java-client/deps`
* `mv rabbitmq-ct-helpers rabbitmq_ct–helpers`
* `make` in `rabbitmq-java-client/deps/rabbitmq_ct_helpers`
* `make` in `rabbitmq-java-client/deps/rabbitmq_ct_helpers/tools/tls-certs` (this step might have been optional)
* shut down my Rabbit server `sudo rabbitmqctl stop`
* `MAKE_VERSION=4.2.1 make tests`, `MAKE_VERSION` is used so that warning about invalid make version is not shown, while gmake is used, which has the correct version, `MAKE_VERSION` is the one that is installed on MAC OS on default

My setup:
* vanilla Erlang 20 from Homebrew
* vanilla RabbitMQ (3.7.0+rc.2.81.ga6a546f) version from Homebrew, no plugins
* vanilla gmake (GNU Make 4.2.1) from Homebrew

**Comment by michaelklishin** [comment]
This client is usually used with [rabbitmq-public-umbrella](https://github.com/rabbitmq/rabbitmq-public-umbrella) by our team. @dumbbell @acogoluegnes would adding a `rabbitmq-ctl-helpers` dependency in this repo make sense to make it easier to use as a standalone project?

**Comment by acogoluegnes** [comment]
@michaelklishin Makes sense, the easier to run the test suite, the better.

**Comment by slayful** [comment]
Thank you for fixing it so quickly! :)
