### ISSUE TITLE
AutomaticRecovery does not re-register all consumers if consumer tag is re-used across channels

### ISSUE THREAD

**Issue by michaeldgagnon** [rabbitmq/rabbitmq-java-client#364]
Using: com.rabbitmq amqp-client 5.2.0
With: RabbitMQ Broker 3.6.15

In the following situation I find auto recovery in the driver does not recover consumers:
1) Make 100 channels
2) Register 1 consumer on each channel with the same consumer tag
3) Force disconnect the connection via the admin console
4) Observe that only 1 consumer is recovered

With 1 change, all consumers will be recovered:
2b) Register 1 consumer on each channel with a unique consumer tag

This is very easy to work around (just use unique tags), but highly painful to diagnose in order to know to do the easy work around.

**Comment by michaelklishin** [comment]
Consumer tracking is per-connection by design. It helps avoid the following scenario:

 * A queue (or anything else) is declared on channel A
 * Then deleted on channel B
 * When A recovers, the queue reappears

**Comment by michaelklishin** [comment]
Reusing consumers tag is not a great idea. You won't be able to tell which consumer it is in the logs, management UI, monitoring data and so on.
