### ISSUE TITLE
Add filter to skip some entities on topology recovery

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-java-client#383]
Topology recovery is all-or-nothing right, there's no way to tweak it. Being able to skip the recovery of some entities could be useful in very specific cases: #382. There's already a way to remove some queues from the recorded queue list: #346. What is considered in this issue is a filter that could be set in the `ConnectionFactory`.

It could be something like this in `4.x.x`:

```java
public interface TopologyFilter {

  <T extends RecordedEntity> boolean shouldRecover(T recordedEntity);

}
```

It would be a `Predicate<? extends RecordedEntity>` in 5.x.

**Comment by acogoluegnes** [comment]
Per discussion with @michaelklishin, an interface with N filter methods each taking an SMI/lambda will do.

**Comment by michaelklishin** [comment]
To clarify: there will be one filter for entity type (queues, exchanges, etc) since having a single lambda without pattern matching will require ugly and error prone switch statements many users would probably rather avoid.
