### ISSUE TITLE
Clarify triple-licensed terms

### ISSUE THREAD

**Issue by guenhter** [rabbitmq/rabbitmq-java-client#416]
According to https://en.wikipedia.org/wiki/Multi-licensing (ok, not the best source but anyway), multi-licensing can mean, that the user has the choice which license is used, or in the other case it can mean that all three licenses must be applied.

This should be clarified. 

Thx

**Comment by michaelklishin** [comment]
It is already clarified [in the docs](http://www.rabbitmq.com/api-guide.html):

```
This means that the user can consider the library to be licensed under any of the licenses from the list above
```

**Comment by michaelklishin** [comment]
Go ahead.
