### ISSUE TITLE
An option to make RpcClient fail early if there are no bindings

### ISSUE THREAD

**Issue by janssk1** [rabbitmq/rabbitmq-java-client#417]
I have noticed that the RpcClient utiltity has no way of using the 'mandatory' flag. 
I would like my RPC call to fail 'fast' in case nobody is listening to the request. Wihout it, i have to wait for the RPC to timeout. 

* RabbitMQ client version 5.5.0

**Comment by michaelklishin** [comment]
A return handler can be registered and either throw/etc or do nothing depending on user-provided values. @acogoluegnes WDYT?

**Comment by acogoluegnes** [comment]
This should be possible as-is:
 * register a `ReturnListener` to the `Channel` instance used for the creation of the `RpcClient`.
 * subclass `RpcClient` and override the `publish` method to publish with the mandatory flag set to true.

**Comment by michaelklishin** [comment]
Arguably the key part here is the `ReturnListener` implementation. If we could come up with a reasonably opinionated implementation that can be used by default the users would appreciate it.

**Comment by acogoluegnes** [comment]
It's straightforward to correlate the original blocking cell in the return listener, so we could unblock the blocking cell and throw an exception or do something else.
