### ISSUE TITLE
[Question] Upgrading java-client version 3.6.x to 5.x.x

### ISSUE THREAD

**Issue by tayfunyasar** [rabbitmq/rabbitmq-java-client#419]
As you described below, Can I upgrade my java-client 4.3.0 to 5.5.0?

https://github.com/rabbitmq/rabbitmq-java-client/releases

Is the client independent from RabbitMQ or not? I couldn't find any detail about it.

My RabbitMQ version is: 3.6.10

**Comment by acogoluegnes** [comment]
The [5.0.0 changelog](https://github.com/rabbitmq/rabbitmq-java-client/releases/tag/v5.0.0) covers breaking changes.

The client is independant from the broker, unless you're using a very old version (RabbitMQ 2.x).

This is [mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) material, please post there for any further question.

**Comment by michaelklishin** [comment]
All key operations will work even against RabbitMQ 2.x. This client won't be able to connect to pre-2.0 brokers.
