### ISSUE TITLE
AMQConnection missing "/" for non-default virtual hosts

### ISSUE THREAD

**Issue by dharrigan** [rabbitmq/rabbitmq-java-client#42]
Hi,

In AMQConnection, line 865, if the virtualHost, is *not* the default, the resultant toString looks something like this:

```
amqp://guest@192.168.80.3:5672test
````

It should be

```
amqp://guest@192.168.80.3:5672/test
```

PR coming shortly.

-=david=-

**Comment by michaelklishin** [comment]
Fixed by #44. Thank you, @dharrigan!

**Comment by dharrigan** [comment]
np :)

**Comment by dumbbell** [comment]
Since RabbitMQ 1.4.0.
