### ISSUE TITLE
Channel#abort discards exceptions which it declares as thrown

### ISSUE THREAD

**Issue by thiagomiranda3** [rabbitmq/rabbitmq-java-client#434]
On the code below that I got from master:
`/** Public API - {@inheritDoc} */
    @Override
    public void abort(int closeCode, String closeMessage)
        throws IOException
    {
        try {
          close(closeCode, closeMessage, true, null, true);
        } catch (IOException _e) {
        /* ignored */
        } catch (TimeoutException _e) {
          /* ignored */
        }
    }`

The method abort throw an IOException that I need to catch when calling this method. But this exception is silently discarded inside them and in the documentation is written that too. So I was suspicious that the documentation was not up to date and had to check the source to verify their validity. Wouldn't be possible to remove this throw? I am not sure with it is necessary in another classes that override this method.

**Comment by acogoluegnes** [comment]
This makes sense, considering the semantics mentioned in the API documentation and the consistency with `Connection#abort`. This is a breaking change though (code catching the `IOException` won't compile anymore), so it must go into 6.0.
