### ISSUE TITLE
Sprious warnings emitted by ClientVersion when the library is relocated

### ISSUE THREAD

**Issue by astei** [rabbitmq/rabbitmq-java-client#436]
If the RabbitMQ library is relocated, it will emit a spurious warning about not being able to find the client version. This is because the property string (`com.rabbitmq.client.version`), is rewritten but `rabbitmq-amqp-client.properties` is not.

This is not a server issue, only a client library issue that does not affect operations, but for completeness:

* RabbitMQ version: 3.7.8
* Erlang version: `Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:64] [hipe] [kernel-poll:true]`
* Other relevant information: https://gist.github.com/astei/1e439c19a29993d9486ff4a5afb9f145
* [Smallest possible reproduction demo](https://github.com/astei/rabbitmq-relocation-bug)
* Client library version (for all libraries used): Java client 5.5.1
* Operating system, version, and patch level: Alpine Linux 3.8.1 on both server and client (we use Kubernetes to run RabbitMQ)

I have a PR to fix this issue, which I will open shortly.

**Comment by acogoluegnes** [comment]
@astei Thanks for this contribution. We'll release 5.5.2 with the fix in the new few days.
