### ISSUE TITLE
Your project rabbitmq/rabbitmq-java-client is using buggy third-party libraries [WARNING]

### ISSUE THREAD

**Issue by FDU-SE-LAB** [rabbitmq/rabbitmq-java-client#438]
Hi, there!
We are a research team working on third-party library analysis. We have found that some widely-used third-party libraries in your project have major/critical bugs, which will degrade the quality of your project. We highly recommend you to update those libraries to new versions.    
We have attached the buggy third-party libraries and corresponding jira issue links below for you to have more detailed information.
  1  commons-cli commons-cli (pom.xml)
  version: 1.1

  Jira issues:
  CLI_1_BRANCH build.xml doesn't work
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-129?filter=allopenissues
  MissingOptionException.getMessage() changed from CLI 1.0 > 1.1
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-149?filter=allopenissues
  Incomplete usage documentation about Java property option
  affectsVersions:1.0;1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-154?filter=allopenissues
  infinite loop in the wrapping code of HelpFormatter
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-162?filter=allopenissues
  PosixParser keeps bursting tokens even if a non option character is found
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-163?filter=allopenissues
  PosixParser ignores unrecognized tokens starting with '-'
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-164?filter=allopenissues
  PosixParser keeps processing tokens after a non unrecognized long option
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-165?filter=allopenissues
  Unable to select a pure long option in a group
  affectsVersions:1.0;1.1;1.2
  https://issues.apache.org/jira/projects/CLI/issues/CLI-182?filter=allopenissues
  Clear the selection from the groups before parsing
  affectsVersions:1.0;1.1;1.2
  https://issues.apache.org/jira/projects/CLI/issues/CLI-183?filter=allopenissues
  Negative arguments should take the priority over numerical options
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-184?filter=allopenissues
  Commons CLI incorrectly stripping leading and trailing quotes
  affectsVersions:1.1;1.2
  https://issues.apache.org/jira/projects/CLI/issues/CLI-185?filter=allopenissues
  Standard help text will not show mandatory arguments for first option
  affectsVersions:1.1
  https://issues.apache.org/jira/projects/CLI/issues/CLI-186?filter=allopenissues

  2  ch.qos.logback logback-classic (pom.xml)
  version: 1.2.3

  Jira issues:
  missing log files and log entries when using SizeAndTimeBasedRollingPolicy 
  affectsVersions:1.2.3
  https://jira.qos.ch/projects/LOGBACK/issues/LOGBACK-1361?filter=allopenissues

Sincerely~
FDU Software Engineering Lab
Jan 7th,2019

**Comment by acogoluegnes** [comment]
Thanks for letting us now. The 2 dependencies you mention (namely Commons CLI and Logback) are test dependencies, so nobody using the Java client in their own project would end up with those dependencies because their dependency manager grabbed them, unless they're added explicitly.

Nevertheless, I removed the code using Commons CLI, as it wasn't used anymore, and got rid of the dependency.
