### ISSUE TITLE
Please handle InterruptedExceptions correctly

### ISSUE THREAD

**Issue by vfelberg** [rabbitmq/rabbitmq-java-client#52]
Class com.rabbitmq.utility.BlockingCell has several while loops catching InterruptedExceptions and ignoring them. This makes it impossible to shutdown the app correctly; you have to kill it brutally. The correct handling of an InterruptedException in a while loop would be:

``` java
try {
  ...
} catch (InterruptedException e) {
  Thread.currentThread().interrupt();
  return;
}
```

There are probably other classes swallowing InterruptedExceptions as well; I'm just reporting the one I found while analyzing what causes our app to hang.

For background info on thread interruption, see e.g.: http://www.ibm.com/developerworks/library/j-jtp05236/

**Comment by michaelklishin** [comment]
@vfelberg yes, you are absolutely correct. By the way, you can submit a pull request that does the changes (against the stable branch), we will evaluate and merge it :)

**Comment by vfelberg** [comment]
Ok, I'll make the fix; it's an easy one :-)

**Comment by michaelklishin** [comment]
I'd like to get this into `3.5.2`, so we'll wait for a PR (or a note that we should handle it in our own).

**Comment by vfelberg** [comment]
Unfortunately, it's not so easy to fix as I thought. I found in total 14 places catching InterruptedException; some of them trivial, most of them not. I guess, some of the core developers need to have a look at those places.

**Comment by michaelklishin** [comment]
@vfelberg I will.

**Comment by michaelklishin** [comment]
@vfelberg can you please reproduce the case when you have your app hanging on shutdown and post a thread dump here?

**Comment by michaelklishin** [comment]
@vfelberg can you please [build from source](http://www.rabbitmq.com/build-java-client.html) on the `rabbitmq-java-client-52` branch and give this updated version a try? See `bin/dist` after `ant dist` finishes. Thank you.
