### ISSUE TITLE
RpcClient requires a different channel per routing key

### ISSUE THREAD

**Issue by janssk1** [rabbitmq/rabbitmq-java-client#639]
Direct-reply allows only one consumer per channel on the 'amq.rabbitmq.reply-to' queue. 

RpcClient creates a consumer during creation, which is fine. However, an RpcClient only allows publishes to one routingKey (the routingKey is also provided as a constructor argument)

Fix is to remove routing key (and exchange as well) from the constructor arguments and allow them to be passed for each invocation. 

* Client library version (for all libraries used)
5.8.0

**Comment by michaelklishin** [comment]
A PR that adds an alternative constructor and invocation constructor would be welcome. Unless @acogoluegnes believe that changing the API entirely is worth doing.

`RpcClient` is primarily an example, it is by no means the One True Way of doing request/reply.

**Comment by acogoluegnes** [comment]
Not sure it's a good idea: as @michaelklishin wrote, `RpcClient` is an example, and its API is already fairly large to cover different cases and examples. Even though it won't break the API, I'm afraid adding yet another method would make this example more cluttered.
