### ISSUE TITLE
Potential deadlock in AutorecoveringConnection

### ISSUE THREAD

**Issue by maxbrodin** [rabbitmq/rabbitmq-java-client#648]
The code in [AutorecoveringConnection.java](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java) acquires synchronization objects in different order (once acquires `consumers` and then `recordedQueues`, another time acquires `recordedQueues` and then `consumers`).

Acquiring synchronization objects in different order can cause circular wait (deadlock).

The first order is: (1) first acquire `consumers` and then `recordedQueues`:
- enter public method `excludeQueueFromRecovery()` at line [984](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L984)
- acquire synchronization on `consumers` at line [987](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L987)
- acquire synchronization on `recordedQueues` at line [988](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L988)

The second order is: (2) first acquire `recordedQueues` and then `consumers`:

- enter public method `recoverQueue()` at line [715](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L715)
- acquire synchronization on `recordedQueues` at line [732](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L732)
- call `deleteRecordedQueue()` at line [740](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L740)
- call `maybeDeleteRecordedAutoDeleteExchange()` at line [973](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L973)
- acquire synchronization on `consumers` at line [1035](https://github.com/rabbitmq/rabbitmq-java-client/blob/91fe55a0b1a6131fe2c4dd110fb71fea908174c6/src/main/java/com/rabbitmq/client/impl/recovery/AutorecoveringConnection.java#L1035)

**Comment by michaelklishin** [comment]
As my investigation in #649 suggests, the right thing to do is to not acquire a lock on `this.consumers` in `AutorecoveringConnection#maybeDeleteRecordedAutoDeleteExchange` instead.
