### ISSUE TITLE
No AMQP 1.0 support

### ISSUE THREAD

**Issue by Heromyth** [rabbitmq/rabbitmq-java-client#651]
I'm not sure about this.

**Comment by michaelklishin** [comment]
This client implements AMQP 0-9-1 and there are no plans to change this. There are existing AMQP 1.0 clients not maintained by our team. Whether there will be an AMQP 1.0 client from our team, time will tell but there are no plans to develop a client for every protocol RabbitMQ supports today or may support in the future. There are also no plans to make a single client support multiple protocols.
