### ISSUE TITLE
Messages out of order when redelivered and consumed with a global prefetch

### ISSUE THREAD

**Issue by sdurrenmatt** [rabbitmq/rabbitmq-java-client#653]
Hi,

I am implementing a queue consumer respecting the following principles:

- Messages must be consumed one by one and in order
- If a message cannot be processed, it is rejected and must be requeued at the same position
- After reaching a certain number of redeliveries, it is rejected without being requeued

In order to achieve this:
- SAC is enabled on the queue, so there can be only one consumer at the same time
- Acknowledgement is manual and prefetch is set to 1, so there can be only one message consumed and processed at the same time
- Since redelivery limit is not a classic queue feature, a redelivery count is maintained to check whether the current message must be requeued or not

Using a local consumer prefetch, everything works properly. However if the prefetch is global, messages are randomly out of order when redelivered and consumed. Is there something I am missing about RabbitMQ channel prefetch mechanism? 

Here are my JUnit tests (one with "local" prefetch and the other with "global" prefetch):

```java
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.rabbitmq.client.Channel;
import com.rabbitmq.client.Connection;
import com.rabbitmq.client.ConnectionFactory;
import com.rabbitmq.client.DeliverCallback;

public class RedeliveryOrderWithQosTest {

    private static final String QUEUE_TEST = "redelivery-order-with-qos-test";

    private static final Integer NB_MESSAGES = 100;

    private Channel channel;

    private static CountDownLatch lock;

    private static Integer redeliveryCount;

    private static Integer messageCount;

    private boolean isOrdered;

    @BeforeEach
    public void setUp() throws Exception {
        // Before each test, create a new connection
        final ConnectionFactory connectionFactory = new ConnectionFactory();
        connectionFactory.setHost("localhost");
        connectionFactory.setPort(5672);
        connectionFactory.setUsername("guest");
        connectionFactory.setPassword("guest");
        connectionFactory.setVirtualHost("/");
        connectionFactory.setAutomaticRecoveryEnabled(true);
        final Connection connection = connectionFactory.newConnection();

        // Create a new channel and queue
        channel = connection.createChannel();
        channel.queueDeclare(QUEUE_TEST, true, false, true, null);

        // Fill the queue with some messages
        for (int i = 0; i < NB_MESSAGES; ++i) {
            channel.basicPublish("", QUEUE_TEST, false, null, String.valueOf(i).getBytes());
        }
    }

    @BeforeEach
    private void initCounts() {
        lock = new CountDownLatch(NB_MESSAGES);
        messageCount = 0;
        redeliveryCount = 0;
    }

    private void consumeWithRedeliveryAndCheckOrder() throws Exception {
        isOrdered = true;

        final DeliverCallback deliverCallback = (consumerTag, delivery) -> {
            // check that message order is preserved			
            final String message = new String(delivery.getBody());
            System.out.println("Consuming message " + message);
            isOrdered &= Integer.valueOf(message).equals(messageCount);

            final long deliveryTag = delivery.getEnvelope().getDeliveryTag();
            if (redeliveryCount < 10) {
                // redeliver message 10 times
                channel.basicReject(deliveryTag, true);
                ++redeliveryCount;
            } else {
                // reject message and consume next message
                channel.basicReject(deliveryTag, false);
                redeliveryCount = 0;
                ++messageCount;
                lock.countDown();
            }
        };

        channel.basicConsume(QUEUE_TEST, false, deliverCallback, consumerTag -> {});
        lock.await(10000, TimeUnit.MILLISECONDS);
    }

    @Test
    public void testRedeliveryOrderWithLocalPrefetch() throws Exception {
        channel.basicQos(1, false);
        consumeWithRedeliveryAndCheckOrder();
        assertTrue(isOrdered);
    }

    @Test
    public void testRedeliveryOrderWithGlobalPrefetch() throws Exception {
        channel.basicQos(1, true);
        consumeWithRedeliveryAndCheckOrder();
        assertTrue(isOrdered);
    }

}
```

Versions used are RabbitMQ 3.8.3 / Erlang 22.2.6 / RabbitMQ Java Client 5.9.0

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
This client guarantees delivery ordering for a given channel. This only means the order in which the provided callback will be invoked. It matters as much what those callbacks do: they can easily kick-off parallel processing of said deliveries. In which case, there is a pretty obvious race condition. Your code performs no synchronization when updating the counters, which has implications in the above case [of concurrent processing].

RabbitMQ tries to place a requeued message into its original position in the queue regardless of what has triggered the  requeueing: an explicit nack or a channel closure. However, this is not something that can be guaranteed in every case: concurrent enqueueing, requeueing, deliveries, and positive acknowledgements all modify relative positions of queue elements.

[Take a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html) and see for yourself what RabbitMQ actually delivers and what the client actually acknowledges. Unlike application-level tests, which are prone to concurrency hazards and incorrect or incomplete interpretation, a traffic capture is as close as it gets to a linearized history of events on both sides.
