### ISSUE TITLE
Why doesn't have IMQImpl in the master?

### ISSUE THREAD

**Issue by BugCui** [rabbitmq/rabbitmq-java-client#684]
Why doesn't have IMQImpl in the master?

**Comment by michaelklishin** [comment]
I will convert this issue to a GitHub discussion. Currently GitHub will [automatically close and lock the issue](https://github.com/github/feedback/discussions/3197) even though your question will be transferred and responded to elsewhere. This is to let you know that we do not intend to ignore this but this is how the current GitHub conversion mechanism makes it seem for the users :(
