### ISSUE TITLE
Does 'Clarify the meaning of "triple licensed"' apply to the released versions?

### ISSUE THREAD

**Issue by oneingfw** [rabbitmq/rabbitmq-java-client#705]
Hi all:
Our team has strict legal requirements when using open source saftware.
rabbitmq-java-client's license makes us have some concerns. Although 'Clarify the meaning of "triple licensed"' submitted in Nov 22,2020, but there is no such sentence in the license file of  released versions.

May I get a offical explanation, this 'Clarify the meaning of "triple licensed"' also applies to the released versions.

**Comment by michaelklishin** [comment]
The client has been triple licensed for years. A note explaining what that means was added to avoid answering the same question over and over. It does not change the license(s) applied to the code. "Dual-licensing" and "triple-licensing" are fairly well established terms.

If your team has strict legal requirements, you should be talking to your corporate lawyers, not OSS contributors on the Internet.
