### ISSUE TITLE
Connection timeout not always enforced in NIO mode for SSL connections

### ISSUE THREAD

**Issue by mgrafl** [rabbitmq/rabbitmq-java-client#719]
RabbitMQ Java client version 5.14.0 connection creation can hang forever on defective socket in the following scenario: 
* ConnectionFactory configured with `useNio()`, `useSslProtocol()`, and non-zero timeouts,
* socket channel that does not write any data. 

Environment:
* Java: OpenJDK 11
* OS: Linux CentOS 7 or Windows 10
* RabbitMQ server: any

The defective socket channel occasionally happened in our production environment (possibly caused a by firewall or proxy). 
I was able to reproduce it locally with a socket channel where the _write_ operation always returns 0 bytes written or simply blocks: 

```java
int amqpPort = 5671 // assumes RabbitMQ server running on localhost;
int amqpProxyPort = 15671;

int connectionTimeout = 5_000;
int handshakeTimeout = 2_000;

// Simulate a connection via that doesn't send anything 
// using https://github.com/NetCrusherOrg/netcrusher-java
TransformFilterFactory outgoingTransformFilterFactory = clientAddress -> 
	buf -> {
		try {
			TimeUnit.SECONDS.sleep(20);
		} catch (InterruptedException e) {}
	};

try (var reactor = new NioReactor(); 
		var tcpProxy = TcpCrusherBuilder.builder()
			.withReactor(reactor)
			.withBindAddress(new InetSocketAddress(amqpProxyPort))
			.withConnectAddress("localhost", amqpPort)
			.withOutgoingTransformFilterFactory(outgoingTransformFilterFactory)
			.build()) {

	tcpProxy.open();

	ConnectionFactory factory = new ConnectionFactory();
	factory.setHost("localhost");
	factory.setPort(amqpProxyPort);

	factory.useSslProtocol();
	factory.useNio();

	factory.setConnectionTimeout(connectionTimeout);
	factory.setHandshakeTimeout(handshakeTimeout);

	ExecutorService executorService = Executors.newSingleThreadExecutor();
	Future<Connection> futureConnection = executorService
		.submit(() -> factory.newConnection());
	
	futureConnection.get(15, TimeUnit.SECONDS);
	// Expected: Timeout from RabbitMQ after 5+2 seconds
	// Actual: Timeout from Future after 15 seconds
}
``` 

On initial connection creation, the workaround is to have a separate thread that interrupts connection creation after a timeout. 
But for auto-recovery there is no workaround.

**Comment by acogoluegnes** [comment]
@mgrafl A [5.14.1 snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/rabbitmq/amqp-client/5.14.1-SNAPSHOT/) is available with a fix, can you give it a try?

**Comment by mgrafl** [comment]
Thanks for resolving this so quickly! Looks good to me.
