### ISSUE TITLE
Queue names longer than 255 characters should be rejected early

### ISSUE THREAD

**Issue by garyrussell** [rabbitmq/rabbitmq-java-client#72]
See https://groups.google.com/forum/#!topic/rabbitmq-users/0i22nvdfP-M

When a queue name exceeds 255 chars, an `IllegalArgumentException` is thrown but the channel is not closed; the next operation on the channel hangs.

**Comment by michaelklishin** [comment]
So sounds like we should reject names longer than the spec-dictated limit and not send anything, so the channel remains open. How does that sound @garyrussell?

**Comment by garyrussell** [comment]
Yes, that would work - detect the illegal argument sooner.
