### ISSUE TITLE
Can handleShutdownSignal method catch ShutdownSignalException?

### ISSUE THREAD

**Issue by zfy68** [rabbitmq/rabbitmq-java-client#727]
Exceptions are business logic code：

```java
Connection connection = factory.newConnection();
            Channel channel = connection.createChannel();
            channel.basicQos(1);
            channel.queueDeclare(rabbitMQConfig.getQueueName(), true, false, false, null);
            Consumer consumer = new DefaultConsumer(channel) {
                @Override
                public void handleDelivery(String consumerTag, Envelope envelope, BasicProperties properties,
                                           byte[] body) throws IOException {
                    channel.basicAck(envelope.getDeliveryTag(), false);
                }
                @Override
                public void handleShutdownSignal(String consumerTag, ShutdownSignalException sig) {
                    System.out.println("...");
                }
            };
            channel.basicConsume(rabbitMQConfig.getQueueName(), false, consumer); 
```

Can the handleShutdownSignal method catch the following exception?

```
com.rabbitmq.client.ShutdownSignalException: connection error
at com.rabbitmq.client.impl.AMQConnection.startShutdown(AMQConnection.java:739)
at com.rabbitmq.client.impl.AMQConnection.shutdown(AMQConnection.java:729)
at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:573)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.rabbitmq.client.MissedHeartbeatException: Heartbeat missing with heartbeat = 60 seconds
at com.rabbitmq.client.impl.AMQConnection.handleSocketTimeout(AMQConnection.java:601)
at com.rabbitmq.client.impl.AMQConnection.access$600(AMQConnection.java:61)
at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:564)
... 1 common frames omitted
```

**Comment by zfy68** [comment]
> The consumer shutdown callback is called during the channel shutdown sequence. I could not reproduce locally. Do you have a way to reproduce reliably?

This is difficult and I can't simulate how it happens? Maybe it's related to rabbitmq server.

**Comment by michaelklishin** [comment]
@zfy68 we do not guess on this team. Either provide evidence (steps to reproduce) or we won't be able to do anything about this.

According to the log, a connection that was shutting down also ran into [missing heartbeats](https://rabbitmq.com/heartbeats.html):

```
Caused by: com.rabbitmq.client.MissedHeartbeatException: Heartbeat missing with heartbeat = 60 seconds
```

This would indeed be difficult to time and reproduce but I'm also not sure what can be done about it. A closing connection
can run into exceptions, even if that's unlikely in practice. Other than ignoring them (which is not necessarily a good idea), there isn't anything
meaningful a library can do.

This is my conclusion for now. If you know how to reproduce this scenario, and we can do it, we will file another issue
with all the specifics (assuming there is *something* that can be meaningfully improved)
