### ISSUE TITLE
Automatic recovery is not terminated by Connection.close

### ISSUE THREAD

**Issue by trisport88** [rabbitmq/rabbitmq-java-client#75]
I have encountered a problem with clean tomcat shutdown when a single broker is shutdown before shutting down tomcat.  The connection and channels are configured for auto recovery.  If I startup tomcat (which connects to the broker and declares some exchanges/queues) then shutdown tomcat everything shuts down cleanly BUT if I stop the broker before shutting down then I get the following message:

SEVERE: The web application [/xyz] appears to have started a thread named [AMQP Connection127.0.0.1:5672] but has failed to stop it. This is very likely to create a memory leak

As far as I can tell I am closing the connection and channels (using abort rather than close).

Thanks to the responder on the forum thread (https://groups.google.com/forum/#!topic/rabbitmq-users/JOZl7VCWSNg) I am creating this issue with the hope of getting a fix into the next release.  It is a problem because it leaves tomcat in a half shutdown state (admins might not realise it it has not shutdown properly before attempting to re-start).

**Comment by michaelklishin** [comment]
While making automatic recovery stop after `Connection.close` is a good idea (we do so in the .NET client now), you can use a custom `ThreadFactory` that will produce background threads. The JVM will happily terminate if there are only daemon threads running.

See "Custom Thread Factories" [in the docs](http://www.rabbitmq.com/api-guide.html).

**Comment by michaelklishin** [comment]
Looks like #76 took care of this.

**Comment by michaelklishin** [comment]
Correction: the PR for this that was merged is #77, not #76.
