### ISSUE TITLE
Match pika implementation of URI parsing.

### ISSUE THREAD

**Issue by bwarren2** [rabbitmq/rabbitmq-java-client#78]
As detailed [here](http://stackoverflow.com/a/31567144/2188525), there is a difference in how this library and pika interpret the same URI.  The pika solution seems cleaner, and I wanted to check for interest in my forming a pull request.

If the URI is 
    
    CLOUDAMQP_URL=amqp://guest:guest@localhost:5672/

and the connection is established with 

    factory.setUri(System.getenv("CLOUDAMQP_URL"));

As things stand, this results in a vhost of "" and a connection error in a default rabbitmq setup (which has a default vhost of `/`).  Is there interest in a pull request to return a vhost of `/` instead of "", to make the default behavior match the default rabbitmq setup?

**Comment by michaelklishin** [comment]
This client is the reference implementation for RabbitMQ. Pika must much [ours](https://www.rabbitmq.com/uri-spec.html). Sorry.

**Comment by michaelklishin** [comment]
Note that this change has been discussed multiple times over the years. More often than not we come across clients that have issues around escaping and so on. FWIW we now have a URI parsing spec which is fairly sensible in my opinion. Small differences such as the one above are OK and I agree that Pika's approach is more user friendly. However, at this point it makes more sense for us to stick to the spec we have.

**Comment by bwarren2** [comment]
That makes sense.  I didn't see an open or closed issue about this, so I thought it worth the ask.  Thanks for the perspective!
