### ISSUE TITLE
RabbitMQ Java client library license consultant

### ISSUE THREAD

**Issue by AliredDevils** [rabbitmq/rabbitmq-java-client#909]
Hi RabbitMQ,

    I find that the RabbitMQ Java client library license is tripled-licensed: 
[Apache Public License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html)
[Mozilla Public License 2.0](https://www.mozilla.org/MPL/2.0/)
[GPL 2.0](https://www.gnu.org/licenses/gpl-2.0.html)

   And  "Users can consider the library to be licensed under any of the licenses from the list above."   

  So i want to double confirm that whether it is an official statement that we could choos the Apache Public License 2.0 to follow, and then our product will not be injected by the GPL 2.0 License?

  Looking forward to your reply.Thank you.

**Comment by AliredDevils** [comment]
@michaelklishin @lukebakken can you help for this? thanks

**Comment by michaelklishin** [comment]
This is a statement in the README in the main repo, how can we make it "more official"?

ASL2 and GPLv2 are incompatible if used in the same code are so you have to pick one.

**Comment by michaelklishin** [comment]
Please never use issues for questions, GitHub Discussions have been around for more than a year.
