### ISSUE TITLE
Shut shutdown executor service correctly

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-java-client#91]
We didn't cover this in #87. One sensible strategy would be to count open connections and shut down the service when it reaches zero, while starting it when it goes to a positive number.

**Comment by YannRobert** [comment]
The ```shutdownExecutor``` can be provided by the user. In this case, the user should be responsible to ```shutdown()``` this ```ExecutorService```.
Is there a way to gradually encourage users to provide the ```shutdownExecutor``` so that the framework does not have to create it internally?

**Comment by michaelklishin** [comment]
We can't require this executor and if we use a default, we are responsible for terminating it.

**Comment by michaelklishin** [comment]
Alternatively we can make the executor opt-in, that is, if it is provided then it will be used, if not, we'll create a thread the old fashioned way using the `ThreadFactory` provided.

**Comment by YannRobert** [comment]
That's tough problem to solve, when you don't have a ```destroy()``` method on ```ConnectionFactory```

**Comment by michaelklishin** [comment]
That's why not having a default may be a decent idea. To be honest, this is not a feature request we often hear about and I'm primarily doing this because the issue is more likely to affect PaaS users than anybody else.

**Comment by YannRobert** [comment]
I guess most Applications have ```ConnectionFactory``` lifecycle same as Application lifecycle.

**Comment by michaelklishin** [comment]
@YannRobert yes but there are 7 or so years worth of documentation and examples that do not dispose connection factories in any way, plus several libraries that build on top of this client. Sorry but an explicit resource release method is not an option here.

**Comment by YannRobert** [comment]
I know. Just thinking out loud.

**Comment by michaelklishin** [comment]
@YannRobert please check [this branch](https://github.com/rabbitmq/rabbitmq-java-client/tree/rabbitmq-java-client-91).

**Comment by michaelklishin** [comment]
@YannRobert I decided to proceed with #93. This should give users in constrained environments a way to use any executor they see fit while not changing anything for the rest of the user base. And introduced code complexity is really low IMO.

**Comment by YannRobert** [comment]
Before I saw your last comments, I was thinking about something like this :

```java
    protected void maybeInitializeShutdownExecutor() {
        if(shutdownExecutor == null) {
            // Equivalent to java.util.concurrent.Executors.newCachedThreadPool(java.util.concurrent.ThreadFactory), but providing a maximumPoolSize.
            // This will create new Threads only when needed, or reuse existing Threads if any.
            // Threads will automatically terminate if idling after a while
            ThreadPoolExecutor shutdownThreadPoolExecutor = new ThreadPoolExecutor(0, 4,
                    60L, TimeUnit.SECONDS,
                    new SynchronousQueue<Runnable>(),
                    new ThreadFactory() {
                        public Thread newThread(Runnable r) {
                            return Environment.newThread(threadFactory, r, "SocketCloseWait shutdown monitor", true);
                        }
                    });
            // prestartAllCoreThreads will only be effective if corePoolSize > 0
            // shutdownThreadPoolExecutor.prestartAllCoreThreads();
            this.shutdownExecutor = shutdownThreadPoolExecutor;
        }
    }
```

Your solution is nice. It does not change anything for existing users. No free improvement for them, neither any risk. Way to go.

**Comment by michaelklishin** [comment]
@YannRobert perfect, thank you for your feedback, a couple of recent changes ended up better than my original versions thanks to it.
