### ISSUE TITLE
Revert timeout validation introduced in #81/#82

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-java-client#92]
Per discussion with @YannRobert, see https://github.com/rabbitmq/rabbitmq-java-client/commit/49d291103ebcf4df80cafa8c4d0c1c594301f398#commitcomment-13363089.

**Comment by YannRobert** [comment]
Milestone is set to 3.6.0
but may be needed in 3.5.5 instead? because
> Fixed in #82, will be 3.5.5

see https://github.com/rabbitmq/rabbitmq-java-client/issues/81#issuecomment-134608328

**Comment by michaelklishin** [comment]
Pushed to `stable` without a pull request. Self-QA'ed.
